// Auto-generated by scripts/generate-blog-index.cjs — DO NOT EDIT
export type BlogPostMeta = {
  slug: string
  title: string
  excerpt: string
  date: string
  category: string
  author: string
  tags: string[]
}

export const blogIndex: Record<string, BlogPostMeta[]> = {
  "es": [
    {
      "slug": "buenas-practicas-categorias",
      "title": "Buenas prácticas para categorías",
      "excerpt": "Organiza tus categorías con colores y nombres consistentes.",
      "date": "2025-12-22",
      "category": "Organización",
      "author": "Goals Team",
      "tags": [
        "categorías"
      ]
    },
    {
      "slug": "configura-presupuesto-mensual",
      "title": "Configura tu presupuesto mensual",
      "excerpt": "Aprende a definir un presupuesto por mes y año para controlar el gasto.",
      "date": "2025-12-22",
      "category": "Finanzas",
      "author": "Goals Team",
      "tags": [
        "presupuesto",
        "consejos"
      ]
    },
    {
      "slug": "exporta-datos-excel",
      "title": "Exporta tus datos a Excel",
      "excerpt": "Exporta tu historial y reportes para compartir o analizar.",
      "date": "2025-12-22",
      "category": "Herramientas",
      "author": "Goals Team",
      "tags": [
        "exportación"
      ]
    },
    {
      "slug": "planes-de-ahorro-metas-progreso",
      "title": "Planes de ahorro: metas y progreso",
      "excerpt": "Crea metas de ahorro, registra contribuciones y sigue tu avance.",
      "date": "2025-12-22",
      "category": "Ahorro",
      "author": "Goals Team",
      "tags": [
        "ahorro",
        "metas"
      ]
    }
  ],
  "en": [
    {
      "slug": "category-best-practices",
      "title": "Category best practices",
      "excerpt": "Organize your categories with consistent names and colors.",
      "date": "2025-12-22",
      "category": "Organization",
      "author": "Goals Team",
      "tags": [
        "categories"
      ]
    },
    {
      "slug": "export-your-data-to-excel",
      "title": "Export your data to Excel",
      "excerpt": "Export your history and reports to share or analyze.",
      "date": "2025-12-22",
      "category": "Tools",
      "author": "Goals Team",
      "tags": [
        "export"
      ]
    },
    {
      "slug": "saving-plans-goals-progress",
      "title": "Saving plans: goals and progress",
      "excerpt": "Create saving goals, record contributions and track your progress.",
      "date": "2025-12-22",
      "category": "Savings",
      "author": "Goals Team",
      "tags": [
        "saving",
        "goals"
      ]
    },
    {
      "slug": "set-your-monthly-budget",
      "title": "Set your monthly budget",
      "excerpt": "Learn how to define a monthly budget by month and year.",
      "date": "2025-12-22",
      "category": "Finance",
      "author": "Goals Team",
      "tags": [
        "budget",
        "tips"
      ]
    }
  ]
}
